Criação de Ícone para indicativo de processo enviado por meio do Tramita.GOV.BR
pengovbr/mod-sei-pen pull request #232
Opened 2023-03-09 12:51 UTC by Mauro1706

2023-05-23 22:57 UTC, guilhermeadc commented
Pull Request atualizado na branch review/sprint7-16 para validação em ambiente de homologação.

2023-05-26 19:59 UTC, gicastephanou commented
Prezados,
Estou replicando a mensagem do Guilherme Cantoni, que está na issue #226.

"Prezados,

Foi identificado um problema semelhante a implementação da issue https://github.com/supergovbr/mod-sei-pen/issues/12 - Ícone indicativo de processo recebido pelo Tramita.gov.br

Durante os testes desta funcionalidade, foram identificados um pequeno problema que precisa ser ajustado antes de serem aceitos e incorporados ao mod-sei-pen.

O ícone indicativo de processo enviado pelo Tramita.gov.br está se repetindo inúmeras vezes, 1 para cada trâmite já realizado pelo processo, conforme demonstrado abaixo.
O comportamento correto deveria ser a apresentação de apenas 1 ícone indicando que o último envio."

2023-05-26 21:07 UTC, gicastephanou requested changes
Prezado Mauro,
Nos testes de validação, foi verificada a mesma falha: duplicidade no ícone para indicativo de processo enviado por meio do Tramita.
<img width="226" alt="image" src="https://github.com/supergovbr/mod-sei-pen/assets/131198162/a2c97378-e616-4061-b6c6-02ec17b76a70">

2023-05-31 20:03 UTC, guilhermeadc commented
Prezado, 

Após reunião com o PO do projeto, foi identificado a necessidade de duas mudanças:
1 - Modificar o ícone para diferenciar tanto o envio, como o recebimento. (Ícones repassados em Teams)
2 - Modificar a regra de exibição para mostrar o ícone pertinente à última operação executada, conforme exemplificado abaixo:

* Processo em tramitação externa e sem confirmação de recebimento do destinatário ('PEN_PROCESSO_EXPEDIDO') : ícone de envio externo (seta para cima)
* Processo recebido externamente ('PEN_PROCESSO_RECEBIDO')  : ícone de recebimento externo (seta para baixo)
* Processo em primeira tramitação externa e posteriormente cancelado ('PEN_PROCESSO_CANCELADO') : Sem ícone
* Processo recebido externamento e posteriormente enviado para outro órgão ('PEN_PROCESSO_EXPEDIDO') : ícone de envio externo (seta para cima)
* Processo recebido,  posteriormente enviado para outro órgão e cancelado ('PEN_PROCESSO_EXPEDIDO') :  ícone de recebimento externo (seta para baixo)
* Processo enviado e posteriormente recusado pelo destinatário ('PEN_PROCESSO_RECUSADO'): Sem ícone
* Processo recebido, posteriormente enviado para outro órgão e rejeitado pelo destinatário : ícone de envio externo (seta para cima

Tratar Tarefa PROCESSO_ABORTADO da mesma forma que PROCESSO_CANCELADO.

2023-08-15 14:08 UTC, merged