mudanca nome Processo Eletronico Nacional(PEN) para Tramita.GOV.BR
pengovbr/mod-sei-pen pull request #240
Opened 2023-03-16 16:42 UTC by michael-ferreira2022

#237

2023-03-18 02:21 UTC, caduvieira requested changes
Foi removido a versão 3.2.1, 3.2.2 e 3.2.3. Por favor enviar somente as mudanças e não os arquivos por completo substituindo os scripts de atualização.

2023-03-18 02:24 UTC, caduvieira commented
E por favor seguir o conventional comitê na mensagem dos commits

2023-03-18 02:25 UTC, caduvieira commented
Não encontrei a mudança de nome do menu. E não houve necessidade de mudança nos testes?

2023-03-21 19:43 UTC, michael-ferreira2022 commented
> Por favor não alterar os itens passados como a versão 1.0.0 do script de atualização. O script de atualização só executa da versão maior atual para frente. Ao executar essa alteração do código a partir de uma versão já instalada você conseguiu alterar o menu?

No ambiente de desenvolvimento quando necessitamos instalar um módulo fazemos a instalação através dos scripts via make file. Como executamos a maioria das vezes como uma nova instalação aqui ele funcionou desta forma.

2023-03-21 19:54 UTC, caduvieira commented
> No ambiente de desenvolvimento quando necessitamos instalar um módulo fazemos a instalação através dos scripts via make file. Como executamos a maioria das vezes como uma nova instalação aqui ele funcionou desta forma.

Por favor instalar a versão 3.2.3 e executar para a nova versão.

2023-10-31 19:38 UTC, sergioadao requested changes
@Mauro1706 ....Segue erro encontrado na aplicação do PULL REQUEST 240

![image](https://github.com/pengovbr/mod-sei-pen/assets/87815724/5579a500-a873-4993-aee8-926706a131af)

![image](https://github.com/pengovbr/mod-sei-pen/assets/87815724/7a991183-5bd1-4220-8f83-580c10f85969)

2023-11-16 17:33 UTC, mateussbh requested changes
Prezados, favor deixar no PR somente os arquivos alterados com escopo relacionado à issue em questão. No PR observa-se que a maioria das alterações são de espaços. Esse excesso de arquivos alterados somente com alterações de espaço aumentará as chances de conflitos na criação da release e dificultará esta etapa.

Outra necessidade de atuação é sobre a resolução do conflito da branch. Favor resolver este conflito para que possamos dar continuidade à validação.

Favor também informar quais itens foram atendidos, quanto ao checklist informado pelo Guilherme Cantoni diretamente na issue.

2024-01-30 13:59 UTC, NinetiesPaul commented
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/427

2024-01-30 13:59 UTC, closed without merging