261 melhoria da mensagem alteração na ordem de documentos do processo indicar ordem
pengovbr/mod-sei-pen pull request #269
Opened 2023-04-24 12:17 UTC by michael-ferreira2022

2023-05-23 22:55 UTC, guilhermeadc commented
Pull Request atualizado na branch review/sprint7-16 para validação em ambiente de homologação.

2023-06-02 21:43 UTC, guilhermeadc commented
Esta Issue foi marcada com contendo Impedimentos devido a problemas de formatação da mensagem indicativa de mudança de ordem dos documentos. Esta é uma limitação do componente de Barra de Progresso utilizada pelo próprio SEI e, com isso, o desenvolvimento solicitado ficou limitado.

Será necessário uma nova avaliação pela equipe da CGSIS para passar uma outra solução técnica para este problema de formatação.

2023-06-05 14:40 UTC, davidnascimento1618 commented
Foi verificado que a mensagem que está sendo exibida para o usuário, está ficando muito extensa, principalmente quando há uma quantidade considerável de documentos anexados ao processo, esta mensagem, além de apontar o problema, tem o intuito de orientar o usuário para a devida solução deste, isto é, da ordenação íntegra destes documentos dentro do processo. Analisaremos internamente uma melhor forma de tratar tal questão.

2023-06-27 04:07 UTC, davidnascimento1618 requested changes
Caro @michael-ferreira2022, foi verificado que a mensagem de alteração da ordem nos documentos, não está orientando o usuário corretamente, no exemplo da evidência abaixo, mostra um processo com três documentos onde um documento foi deslocado da posição 3 para a posição 1 e, consequentemente, o documento que estava na posição 1 foi para a posição 2 e o de posição 2 para a posição 3, no entanto, o que aconteceu é que o sistema informou que o documento que estava na posição 3 mudou da posição 1 para a 2, o que está errado, ademais, mesmo realizando a alteração sugerida pela mensagem e reenviando o processo, o sistema exibiu a próxima mensagem sem quaisquer sugestão de resolução.

https://github.com/supergovbr/mod-sei-pen/assets/87980947/c7b7b36b-724a-4389-951e-68aafd024a7e

2023-06-29 20:11 UTC, davidnascimento1618 requested changes
Prezado @michael-ferreira2022, no reteste foi verificado que, a mensagem de alteração da ordem nos documentos, continua incorreta, no exemplo da evidência abaixo, mostra um processo com três documentos onde um documento foi deslocado da posição 3 para a posição 1 e, consequentemente, o documento que estava na posição 1 foi para a posição 2 e o de posição 2 para a posição 3, no entanto, o que aconteceu é que o sistema informou que o documento que estava na posição 3 mudou da posição 1 para a 2, o que está errado, ademais, o sistema acusou um número de documento que não existe na lista em questão, ao invés dele informar que seria o documento de '0000012' que foi alterado, ele indicou que seria o documento de número '000014'.

https://github.com/supergovbr/mod-sei-pen/assets/87980947/745faf03-7731-488b-bc84-ead2b193f6e9

2023-08-15 00:15 UTC, davidnascimento1618 requested changes
@michael-ferreira2022:

1. Adicionar um caso de teste, conforme o cenário descrito nos _steps_ do [comentário](https://github.com/pengovbr/mod-sei-pen/issues/261#issuecomment-1678234563) da _issue_ em questão;
2. Ajustar o teste conforme o padrão, no tocante à nomenclatura dos arquivos e classes, ou seja, o certo seria 'TramiteReordenarProcessoTest' ao invés de 'ReordenarProcesso';
3. Corrigir a seguinte falha na execução do teste em questão:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/251a7f36-2a3a-4e59-ac50-f30974838458)

4. Após a execução bem sucedida dos testes, gravar um evidência em vídeo e anexar na _issue_ correlacionada.

2023-10-02 18:34 UTC, davidnascimento1618 requested changes
Prezado, @michael-ferreira2022, ao tentar atualizar a _branch_ em meu ambiente local, houve alguns conflitos nos arquivos: _ProcessoEletronicoRN.php_ e _ExpedirProcedimentoRN.php_, como você pode observar no _print_ abaixo, assim que corrigi-los, favor sinalizar para que eu possa realizar os retestes descritos neste no [comentário supracitado](https://github.com/pengovbr/mod-sei-pen/pull/269#pullrequestreview-1577820757).

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/e64e414e-5338-4192-ac5f-5abb4233f28c)

2023-11-02 03:56 UTC, davidnascimento1618 requested changes
Prezados, conforme exibido no _print_ abaixo, ao tentar atualizar a _branch_ localmente, houve alguns conflitos nas classes: _ProcessoEletronicoRN_ e _ExpedirProcedimentoRN, assim que corrigi-los, favor sinalizar para que eu possa realizar os retestes na _issue_ correlacionada.

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/d9e6905f-0d46-4cfc-a446-edf4ec988ffe)

2023-11-02 05:40 UTC, davidnascimento1618 requested changes
Prezados, favor verificar os seguintes itens e corrigi-los:

- [ ] **1.** Atribuir um nome mais intuitivo ao teste (isso inclui nomenclatura dos arquivos e classes correlacionadas), ou seja, uma sugestão seria: '_TramiteReordenarDocumentosProcessoTest_' ao invés de '_ReordenarProcesso_';
- [ ] **2.** Adicionar um _test case_ ao _[functional test](https://github.com/pengovbr/mod-sei-pen/pull/269/files#diff-97b750ea4fd04ba64f970824fd10e0a72434f82676654677243c30ab83db870f)_, conforme o cenário descrito nos _steps_ deste [comentário](https://github.com/pengovbr/mod-sei-pen/issues/261#issuecomment-1678234563);
- [ ] **3.** Não foi encontrado o teste funcional para a versão 3 do SEI;
- [ ] **4.** Não foi encontrado o teste funcional para a versão 4 do SEI.

2024-01-26 19:34 UTC, Mauro1706 commented
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/425

2024-01-26 19:34 UTC, closed without merging