196 limitacoo de repositorios unidades para o envio de processo
pengovbr/mod-sei-pen pull request #274
Opened 2023-05-03 21:33 UTC by Mauro1706

2023-05-29 19:10 UTC, davidnascimento1618 requested changes
Foi verificado ao clicar no botão de envio de processo para um órgão externo e ao acessar a tela de mapeamento de unidades, está ocasionando erro, como mostra no _.gif_ abaixo:

![Erro ao clicar no botão de envio de processo para um órgão externo e ao acessar a tela de mapeamento de unidades](https://github.com/supergovbr/mod-sei-pen/assets/87980947/69d434f8-fcbb-4b5d-9004-8a5644ba2bb5)

2023-05-30 19:06 UTC, davidnascimento1618 requested changes
Favor corrigir as versões do módulo para 3.4.0 no script de atualização do SEI (sei_atualizar_versao_modulo_pen.php) e no arquivo PENIntegracao.php

2023-05-30 20:58 UTC, davidnascimento1618 requested changes
Prezado, foi verificado que o campo 'Unidade', na tela de 'Envio Externo de Processo', não está respeitando a pesquisa utilizando a função de _autocomplete_, ou seja, mesmo escrevendo parte da palavra de uma unidade que não encontra-se cadastrada como restritiva, no mapeamento de unidades, o sistema está retornando no resultado a unidade restritiva.

Segue abaixo um _.gif_ evidenciando tal problema:

![Campo 'Unidade' não está respeitando o autocomplete](https://github.com/supergovbr/mod-sei-pen/assets/87980947/5963ebb1-aacc-471b-8f83-f0009a050a69)

2023-06-19 22:03 UTC, Mauro1706 commented
> Prezado, foi verificado que o campo 'Unidade', na tela de 'Envio Externo de Processo', não está respeitando a pesquisa utilizando a função de _autocomplete_ , ou seja, mesmo escrevendo parte da palavra de uma unidade que não encontra-se cadastrada como restritiva, no mapeamento de unidades, o sistema está retornando no resultado a unidade restritiva.
> 
> Segue abaixo um _.gif_ evidenciando tal problema:
> 
> ![Campo 'Unidade' não está respeitando o preenchimento automático](https://user-images.githubusercontent.com/87980947/242095566-5963ebb1-aacc-471b-8f83-f0009a050a69.gif)

@davidnascimento1618 o objetivo da implementação falado em reunião com Guilherme Cantoni foi restringir as unidades que o usuário pode enviar, portanto se não for selecionado nenhuma estrutura e unidade ele pode enviar a qualquer uma disponível! Foi acordado que e mais comum limitar a uma unidade e e subir a quantidade quando for solicitado!

2023-06-26 20:03 UTC, davidnascimento1618 reviewed
@Mauro1706, conforme a reunião de _review_ da última sexta-feira, ficou acordado a atualização do PR em questão para tratar o problema supracitado (função de _autocomplete_ não está funcionando como deveria).

Outro problema encontrado foi na tela de 'Mapeamento de Unidade', onde o sistema está exibindo, no campo de pesquisa (via função _autocomplete_) 'Unidades do PEN (Estruturas Organizacionais)', uma unidade a qual já foi vinculada e, consequentemente, acaba ocasionando um erro em tela, conforme é exibido no vídeo abaixo:


https://github.com/supergovbr/mod-sei-pen/assets/87980947/bd17c634-fa48-43ba-a96b-c40d430d5904

2023-07-25 22:29 UTC, davidnascimento1618 requested changes
Prezado @Mauro1706, foi constatada mais quatro inconsistências, são elas:

1. Está ocasionando um erro intermitente no carregamento das estruturas: _"Erro processando operação "processarControladorAjax" no módulo "Integração Processo Eletrônico Nacional - PEN"."_;

2. A mensagem de impedimento (ao tentar carregar uma unidade sem o repositório de estruturas selecionado) está errada, deveria ser: "Nenhum Repositório de Estruturas selecionado." ao invés de "Nenhum RepoEstruturas selecionado.";

3. O _hint_ do botão remover deveria ser: "Remover Estruturas Selecionadas" ao invés de "Remover Estrutuas Selecionados";

4. Para manter o mesmo padrão de restrição de unidades, deixar todo o início de palavra em maiúsculo, na mensagem que informa quando o repositório de estruturas não foi encontrado, ou seja, deveria estar descrito da seguinte forma: "Repositório de Estruturas não Encontrado", ao invés de: "Repositório de estruturas não Encontrado".

https://github.com/supergovbr/mod-sei-pen/assets/87980947/e2eb84b9-b72a-41ba-b014-082bd7c31236

2023-08-11 20:44 UTC, davidnascimento1618 requested changes
Ao retestar, foi verificado que o sistema não está removendo as unidades ao salvar uma edição de restrição de unidades do mapeamento, ademais, o sistema está replicando as unidades a cada reedição e salvamento, como é exibido no .gif_ abaixo:

https://github.com/pengovbr/mod-sei-pen/assets/87980947/e2c54281-7844-4843-877b-a2d51fccbd58

2023-08-29 19:54 UTC, davidnascimento1618 requested changes
Prezado @Mauro1706, após novos testes realizados, identifiquei três problemas, são eles:

1. Ao adicionar unidades restritivas a algum repositório (a partir do segundo adicionado em diante), o sistema está deletando todas as unidades restritivas da lista, como se pode observar no vídeo com a evidência abaixo:

https://github.com/pengovbr/mod-sei-pen/assets/87980947/ac66ea02-3bd6-4884-a333-65d8885ea996

2. Ao editar um mapeamento existente para excluir uma unidade restritiva da lista, o sistema está removendo os repositórios não correlacionados, ou seja, considerando a seguinte relação: A -> X; B -> Y; e C -> Z, caso o usuário exclua a unidade X, ao salvar e voltar à tela (via edição), o sistema está removendo os repositórios B e C, em vez de remover apenas o A.
Evidência do problema:


https://github.com/pengovbr/mod-sei-pen/assets/87980947/9c5ccef4-058e-4a1f-a4c4-d5c9dca2cbd9

3. Outro ponto que deve ser salientado, seria com relação ao tempo que um repositório e uma unidade estão sendo carregados, observa-se que entre a digitação, o carregamento e a exibição, está se gastando em torno de 5 segundos, o que antes essa operação era quase que imediata, mesmo digitando parte da palavra, ademais, o sistema não está mais exibindo o ícone de carregamento.

2024-01-19 18:41 UTC, Mauro1706 commented
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/423

2024-01-19 18:41 UTC, closed without merging