mensagem e log tramite em andamento
pengovbr/mod-sei-pen pull request #283
Opened 2023-05-18 17:20 UTC by michael-ferreira2022

#273

2023-05-31 21:22 UTC, guilhermeadc requested changes
Prezado Michael, 

Durante a revisão do código pela equipe,  vários problemas foram identificados nesta implementação e serão pontuados nas respectivas linhas na revisão do Github.

Em geral, a implementação deveria ser bem simples:
1 - Verificar se ocorreu erro 'já possui trâmite em andamento' na chamada da API do tramita
2 - Lançar exceção com mensagem sugerida orientando o usuário sobre o que deveria ser feito 
"O trâmite ainda não foi concluído. Acompanhe no Painel de Controle o andamento da tramitação, antes de realizar uma nova tentativa...

Foi identificado a criação do método `validarTramitaEmAndamento` para tratar esta mensagem, mas ele contem vários erros e vejo que não é necessário, já que a variável `$parametros` passado para a funcão enviarProcesso já possui todas as informações para formatar a mensagem.

2023-05-31 21:22 UTC, guilhermeadc commented on src/rn/ProcessoEletronicoRN.php
> +                $strMensagem = $this->validarTramitaEmAndamento($parametros->dblIdProcedimento, $strMensagem);
Neste ponto já poderia ser feito o tratamento para lançar a exceção com a mensagem sugerida nas especificações. O **NRE** e **Protocolo Formatado do Processo** podem ser obtido da variável `$parametros`.

2023-05-31 21:22 UTC, guilhermeadc commented on src/rn/ProcessoEletronicoRN.php
> +                $e->faultstring = $strMensagem;
Não identificamos o motivo para esta atribuição.

2023-05-31 21:22 UTC, guilhermeadc commented on src/rn/ProcessoEletronicoRN.php
> +        $objUltimoTramiteDTO = $objProcessoEletronicoRN->consultarUltimoTramite($objProcessoEletronicoDTO);
Não é necessário acessar novamente a API do Tramita para buscar informações do último trâmite, já que o NRE é conhecido na base de dados do sistema e em variável disponível no contexto.

2023-05-31 21:22 UTC, guilhermeadc commented on src/rn/ProcessoEletronicoRN.php
> +            $objAtividadeDTO->retDblIdProcedimentoProtocolo();
Este bloco de código não está fazendo nada, pois o objeto `$objAtividadeDTO` é preenchido mas não utilizado posteriormente em pesquisas.

2023-05-31 21:22 UTC, guilhermeadc commented on src/rn/ProcessoEletronicoRN.php
> +
Além de não ser necessário buscar na base de dados os dados deste processo para exibição do número do processo, outros pontos devem ser avaliados.

- Como a intenção da consulta é retornar apenas 1 registro, não deve ser utilizado o método `listar`, mas sim, o método `consultar`. Isso deve ser verificado nas próximas implementações.
- Na linha 587 foi definido para retornar todos os campos da tabela de protocolo, para no final utilizar apenas um campo. Isto não deve ser feito, sendo necessário indicar apenas os campos que serão efetivamente utilizados. 
Ex: $objProtocoloDTO->retStrProtocoloFormatado()

2023-06-28 05:45 UTC, davidnascimento1618 reviewed
Prezado @michael-ferreira2022, as solicitações supracitadas pelo Guilherme Cantoni foram implementadas? Questiono-o pelo fato do último _commit_ ter sido realizado no dia 18/05, às 14:19, e as solicitações terem sido realizadas 13 dias depois, ou seja, no dia 31/05.

2023-08-15 14:48 UTC, closed without merging