153 criar criticas para impedir desativar ou excluir na administracao do modulo pen
pengovbr/mod-sei-pen pull request #284
Opened 2023-05-18 20:04 UTC by Mauro1706

Este pull request tem como dependência o pull requst do super https://github.com/supergovbr/super/pull/253

2023-06-01 21:25 UTC, guilhermeadc requested changes
Prezado, 

Toda esta implementação deverá ser revisada com a equipe de desenvolvimento por conter problemas na validação da funcionalidade, como problemas na estratégia de implementação. 

Peço que reuna com a equipe para revisar os pontos a serem modificados.

2023-06-01 21:25 UTC, guilhermeadc commented on src/PENIntegracao.php
> +      $objPenRelTipoDocMapEnviadoDTO->retTodos();
Não deve ser utilizado a recuperação de todos os campos da tabela apenas para consumir uma única propriedade do objeto. Utilizar a funcão corresponde no DTO para indicar a recuperação do campo necessário. Neste caso, poderia ser utilizado o método contar() para localizar se o item existe na base de dados:

$objPenRelTipoDocMapEnviadoRN->contar($objPenRelTipoDocMapEnviadoDTO);

2023-06-01 21:25 UTC, guilhermeadc commented on src/PENIntegracao.php
> +      if (!is_null($objPenRelTipoDocMapEnviadoDTO)) {
Não deve ser utilizado a recuperação de todos os campos da tabela apenas para consumir uma única propriedade do objeto. Utilizar a funcão corresponde no DTO para indicar a recuperação do campo necessário. Neste caso, poderia ser utilizado o método contar() para localizar se o item existe na base de dados:

$PenRelTipoDocMapRecebidoRN->contar($PenRelTipoDocMapRecebidoDTO);

2023-06-01 21:25 UTC, guilhermeadc commented on src/PENIntegracao.php
> +      $objPenHipoteseLegalDTO->retTodos();
mesmo comentário dos itens anteriores.

2023-06-01 21:25 UTC, guilhermeadc commented on src/PENIntegracao.php
> +      $objPenUnidadeDTO->retTodos();
mesmo comentário dos itens anteriores.

2023-06-01 21:25 UTC, guilhermeadc commented on src/rn/VerificadorInstalacaoRN.php
> +
Não identificamos o que esta implementação está relacionada com a crítica de ativação ou desativação dos itens.

2023-06-01 21:25 UTC, guilhermeadc commented on src/rn/VerificadorInstalacaoRN.php
> +    }
Não identificamos o que esta implementação está relacionada com a crítica de ativação ou desativação dos itens. 
Aparentemente, foram enviadas duas implementações distintas, o que impede o merge deste Pull Request por conter outra implementação fora do contexto.

2023-06-28 13:07 UTC, michael-ferreira2022 commented
Esta funcionalidade do PR [#280](https://github.com/supergovbr/super/pull/280) realizado no projeto Super.

2023-09-21 04:27 UTC, davidnascimento1618 requested changes
Prezado, @michael-ferreira2022, ao tentar atualizar a _branch_ localmente, houve alguns conflitos nos arquivos: _VerificadorInstalacaoRN.php_ e _PENIntegracao.php_, como você pode observar no _print_ abaixo, assim que corrigi-los, favor sinalizar para que eu possa realizar os retestes na _issue_ correlacionada.

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/df9ae7fd-283e-4251-aa52-a6a1162c9887)

2023-10-30 17:22 UTC, davidnascimento1618 requested changes
Prezados, favor verificar a necessidade desse trecho de código abaixo ter sido incluído na classe _PenHipoteseLegalRN_:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/2a49ec09-6358-4d00-b0fb-00df7f9bd3da)

Outro ponto que deve ser tratado, seria com relação a remoção de classes, métodos, variáveis e outros arquivos correlacionados à entidade 'Hipótese Legal', ou seja, todo o código precisa ser removido deste _pull request_ em questão, uma vez que não há ponto de extensão para hipótese legal (como mencionado neste comentário [aqui](https://github.com/pengovbr/mod-sei-pen/issues/153#issuecomment-1672495528)), foi criado o _PR_ #358 para isso, pertinente à _issue_ #348.

2024-03-26 14:54 UTC, closed without merging

2024-03-26 14:54 UTC, Mauro1706 commented
Implementação realizada no PR #462