250 mapeamento de tipos de processos cadastrar orgao externo
pengovbr/mod-sei-pen pull request #316
Opened 2023-07-03 21:19 UTC by Mauro1706

Closes: #250

2023-08-16 03:17 UTC, davidnascimento1618 requested changes
1. Ajustar o teste conforme o padrão, no tocante à nomenclatura dos arquivos e classes correlacionadas, ou seja, o certo seria '_TramiteMapeamentoOrgaoExternoTest_' ao invés de '_MapeamentoOrgaoExterno_';

2. Corrigir a seguinte falha na execução do teste em questão:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/08748475-e47d-43be-adff-c3f49e74a4b1)

3. Após a execução bem sucedida dos testes, gravar um evidência em vídeo e anexar na _issue_ correlacionada.

2023-08-21 14:07 UTC, Mauro1706 commented
https://github.com/pengovbr/mod-sei-pen/assets/83025710/274d4409-e9bf-4fc6-8d4a-a4d29385c1da

Segue evidência de funcionamento de testes
Caso o erro persista, rodar "composer dumpautoload"

2023-08-23 19:49 UTC, davidnascimento1618 reviewed
_Steps_ para executar o teste automático:


1. No SIP, atribuir todos os recursos do tipo _pen_map_orgaos_externos_ ao perfil 'Básico' (Perfis -> Listar -> 'Básico' -> Montar Perfil);
2. Caso não esteja configurado, atribuir o 'ID' e 'Nome' das estruturas (unidades) no arquivo _phpunit.xml_ (linhas 36, 39, 42 e 44);
3. Executar o comando: _make teste=TramiteMapeamentoOrgaoExternoTest test-functional_
4. Caso apresente erro, executar o comando: _sudo composer dump-autoload_ no seguinte _path_: ../super/src/sei/web/modulos/mod-sei-pen/tests_super/funcional (caso o _composer_ esteja instalado, senão, instalá-lo).

2023-09-22 02:23 UTC, davidnascimento1618 requested changes
Prezado, @Mauro1706, ao tentar atualizar a _branch_ localmente, houve alguns conflitos nos arquivos: _sip_atualizar_versao_modulo_pen.php_, _sei_atualizar_versao_modulo_pen.php_, _VerificadorInstalacaoRN.php_ e _PENIntegracao.php_, como você pode observar no _print_ abaixo, assim que corrigi-los, favor sinalizar para que eu possa realizar os retestes na _issue_ correlacionada.

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/e64e414e-5338-4192-ac5f-5abb4233f28c)

2023-10-04 07:51 UTC, davidnascimento1618 requested changes
Prezado, @Mauro1706, favor corrigir a seguinte falha na execução do _functional test_:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/ec8851e1-040a-4790-9f8d-706075358501)

2023-10-04 14:45 UTC, Mauro1706 commented
Parra corrigir o intem https://github.com/pengovbr/mod-sei-pen/pull/316#pullrequestreview-1656876427 deverá rodar o comando "composer dump-autoload"  para incluir o arquivo no autoload.

2023-10-18 20:23 UTC, davidnascimento1618 requested changes
Prezado @Mauro1706, foi verificado que o _assert_ (depois da ação de cadastrar) deverá validar todos os itens da lista que foram incluídos na criação, no caso em questão, seriam os campos: 'Órgão Origem' e 'Órgão Destino', só usar a função _'$this->assertTrue(true)'_ não é o suficiente, porque, por exemplo, se o teste em questão for executado duas vezes, o segundo deverá falhar, porque já existe um registro incluído e, consequentemente, o sistema não permitirá uma nova inclusão, exibindo, desta forma, uma mensagem de impedimento, mas não é o que está ocorrendo, independente de quantas vezes o teste for executado, sempre vai passar.
Um exemplo que pode ser seguido para a implementação da função _assert_, validando cada valor incluído na lista, seria [este](https://github.com/pengovbr/sei/pull/332/files#diff-c87f5a445ed7675a3df781611fc8e94c5c20d266e5c69e8cc955b19fc7d27fc5). 

Outro _test case_ que seria importante ter, é no caso descrito acima, ou seja, validar a tentativa de cadastrar um relacionamento já existente, onde o teste deverá validar não só a presença da mensagem de impedimento (_"Cadastro de relacionamento entre órgãos já existente."_), mas também a **não** inclusão do registro.

2023-10-18 20:45 UTC, davidnascimento1618 requested changes
Favor corrigir o test funcional na versão 4 do SEI, pois houve erro em sua execução:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/ef3bf476-a61a-415c-a885-f462f6d89e54)

2023-10-18 21:13 UTC, davidnascimento1618 requested changes
@Mauro1706, favor corrigir o test funcional da versão **3** do SEI, pois houve erro em sua execução, como você pode observar na ilustração abaixo:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/3fdc232d-4770-4d3c-9539-d45c18c59340)

2023-11-08 16:13 UTC, davidnascimento1618 requested changes
Prezado @Mauro1706,

Abaixo segue uma evidência do erro que está ocorrendo na execução do teste automatizado em questão:


https://github.com/pengovbr/mod-sei-pen/assets/87980947/b1eba52e-9b0a-4988-8ee5-be8de66dff66

2023-11-17 04:29 UTC, davidnascimento1618 requested changes
Prezado @Mauro1706, ao executar o teste funcional (SEI versão "super"), foi constatado erro na execução do _test case_ que testa a exclusão de um mapeamento, como você pode observar na ilustração abaixo, favor corrigir

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/b18cbf80-105b-43d6-b68a-c606a61816f5)

2023-11-17 05:46 UTC, davidnascimento1618 requested changes
@Mauro1706, corrigir o _layout_ do _combobox_ de 'Estado', para a versão 3 do SEI, observe que o mesmo encontra-se com uma borda a mais em seu contorno:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/2c474621-b448-40fb-8553-8e9a560923d3)

2023-11-17 21:09 UTC, davidnascimento1618 requested changes
@Mauro1706, atribuir um nome mais intuitivo aos testes funcionais (isso inclui nomenclatura dos arquivos e classes correlacionadas), ou seja, um sugestão seria: '_MapeamentoTipoProcessoRelacionamentoOrgaosCadastroTest_' ao invés de '_TramiteMapeamentoOrgaoExternoTest_'.

2023-11-24 22:59 UTC, Mauro1706 commented
Devido a grande quantidade de commits foi realizado a correção em um outro PR:
https://github.com/pengovbr/mod-sei-pen/pull/401

2023-11-24 22:59 UTC, closed without merging