251 mapeamento de tipos de processos gerar tela listar
pengovbr/mod-sei-pen pull request #323
Opened 2023-07-13 00:52 UTC by Mauro1706

Closes: #251

2023-08-16 03:20 UTC, davidnascimento1618 requested changes
Corrigir as mesmas inconsistências encontradas conforme o [comentário](https://github.com/pengovbr/mod-sei-pen/pull/316#pullrequestreview-1579735189) do _pull request_ 316.

2023-09-22 02:29 UTC, davidnascimento1618 requested changes
Prezado, @Mauro1706, ao tentar atualizar a _branch_ localmente, houve alguns conflitos nos arquivos: _sip_atualizar_versao_modulo_pen.php_, _sei_atualizar_versao_modulo_pen.php_, _VerificadorInstalacaoRN.php_ e _PENIntegracao.php_, como você pode observar no _print_ abaixo, assim que corrigi-los, favor sinalizar para que eu possa realizar os retestes na _issue_ correlacionada.

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/1ace29bf-1e72-4c9e-9e67-eceaf89e9114)

2023-10-19 01:52 UTC, davidnascimento1618 requested changes
@Mauro1706, favor verificar os seguintes itens e corrigi-los:

- [x] **1.** Erro na execução do teste funcional:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/aa10e9c6-a08c-43ab-b636-dc4af364ba9e)

- [ ] **2.** Atribuir um nome mais intuitivo aos testes funcionais (isso inclui nomenclatura dos arquivos e classes correlacionadas), ou seja, um sugestão seria: '_MapeamentoTipoProcessoRelacionamentoOrgaosListagemImportaçãoTest_' ao invés de _'TramiteMapeamentoOrgaoExternoTest'_;

- [x] **3.** Não foi encontrado o teste funcional para a versão **3** do SEI (apenas o cenário base);

- [x] **4.** Não foi encontrado nenhum artefato de teste para a versão **4** do SEI.

2023-11-17 21:28 UTC, davidnascimento1618 requested changes
Prezado @Mauro1706, foi verificado que os cenários de testes não estão testando a listagem do relacionamento entre órgãos em si, nem tão menos a ação de importação do arquivo _.csv_ e a lista dos tipos de processo no _modal (preview)_ e suas ações (botões de 'Fechar' e 'Prosseguir'), ou seja o teste deveria realizar um _assert_ na listagem dos IDs e tipos de processo que são apresentados dentro do _modal_, onde o resultado destes deverão ser iguais aos que estão contidos respectivamente dentro do conteúdo do arquivo _.csv_.

2023-11-24 22:59 UTC, Mauro1706 commented
Devido a grande quantidade de commits foi realizado a correção em um outro PR:
https://github.com/pengovbr/mod-sei-pen/pull/401

2023-11-24 22:59 UTC, closed without merging