257 importar de tipos de processos
pengovbr/mod-sei-pen pull request #335
Opened 2023-08-04 14:17 UTC by michael-ferreira2022

Closes #257

2023-08-04 18:13 UTC, michael-ferreira2022 commented
[257-importar-de-tipos-de-processos.webm](https://github.com/supergovbr/mod-sei-pen/assets/121502868/2af5eb85-9010-4fc1-9273-1ec9d690fbcf)

2023-08-04 19:00 UTC, michael-ferreira2022 commented
[tipos_processos.csv](https://github.com/supergovbr/mod-sei-pen/files/12263814/tipos_processos.csv)

2023-08-25 00:04 UTC, davidnascimento1618 requested changes
Prezado, @michael-ferreira2022, ao baixar a _branch_ e tentar atualiza-la localmente, houve alguns conflitos, como você pode observar no _print_ abaixo, favor corrigi-los:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/4e5079f6-9510-442e-94ab-5596f9e1afb1)

2023-10-25 16:20 UTC, davidnascimento1618 requested changes
@Mauro1706, favor verificar os seguintes itens e corrigi-los:

- [ ] **1.** Erro na execução do teste funcional:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/af05ab2d-cd94-481f-b64c-972966ccdf09)

- [ ] **2.** Atribuir um nome mais intuitivo ao teste (isso inclui nomenclatura dos arquivos e classes correlacionadas), ou seja, um sugestão seria: '_MapeamentoTipoProcessoImportarArquivoTest_' ao invés de '_MapeamentoOrgaoExterno_';

- [ ] **3.** Não foi encontrado o teste funcional para a versão **3** do SEI (apenas o cenário base);

- [ ] **4.** Não foi encontrado nenhum artefato de teste para a versão **4** do SEI.

2023-11-09 11:44 UTC, closed without merging