337 melhoria mensagem unidade nao configurada para receber processos externos
pengovbr/mod-sei-pen pull request #345
Opened 2023-08-08 18:23 UTC by Mauro1706

Closes: #337

2023-09-11 16:25 UTC, gicastephanou approved these changes
Boa tarde,
A melhoria da mensagem foi realizada.

2023-10-10 05:46 UTC, davidnascimento1618 requested changes
Prezado @Mauro1706, esse trecho de código da imagem abaixo, poderia estar dentro deste _if(!isset($objUnidadeDTO)){...}_

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/41967f03-47d2-4205-89b8-8aa2e48db8ef)

Haja vista que isso evitaria consumo de recurso, pois todas as vezes que passar por esse trecho, o código irá instanciar um objeto desnecessariamente.

Outra questão, seria com relação à classe _VerificadorInstalacaoRN.php_, observa-se que não houve alteração no código, apenas remoção de uma linha, portanto reverter essa alteração e só realizar _commits_ do que de fato for realmente necessário.

2023-11-10 19:01 UTC, merged

2023-11-10 19:56 UTC, caduvieira commented
@Mauro1706 ainda não foi aceito. Por favor refazer o PR

2023-11-10 21:32 UTC, caduvieira commented
Foi feito um force push e esse PR desfeito.

2023-11-13 11:53 UTC, Mauro1706 commented
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/392