344 nova funcionalidade mapeamento de envio parcial
pengovbr/mod-sei-pen pull request #351
Opened 2023-08-17 13:08 UTC by Mauro1706

2023-08-17 13:09 UTC, Mauro1706 commented
Closes: #344

2023-08-18 13:51 UTC, Mauro1706 commented
Evidencia da funcionalidade:

https://github.com/pengovbr/mod-sei-pen/assets/83025710/c68ff97b-ed62-453e-a92f-e344d79ad1dd

2023-08-18 14:08 UTC, Mauro1706 commented
para acesso a funcionalidade seguir os seguintes passos:

Dar permissões de acesso:
**Acessar o sistema SIP**
Menu: Perfis > Listar > Sistema > SEI
Selecionar "Montar Perfil" do Perfil Básico
Pesquisar por recurso: "pen_map_orgaos_externos"

2023-09-08 17:38 UTC, Mauro1706 commented
Closes: #344

2023-09-08 17:38 UTC, Mauro1706 commented
Closes #351

2023-09-08 17:39 UTC, Mauro1706 commented
Closes #344

2023-09-18 14:38 UTC, gicastephanou requested changes
Bom dia,
Favor resolver os conflitos existentes em vários arquivos.

2023-09-19 18:53 UTC, gicastephanou approved these changes

2023-10-09 18:01 UTC, davidnascimento1618 requested changes
@Mauro1706, favor realizar os ajustes elencados abaixo:

- [ ] **1.** Ajustar a nomenclatura do teste para manter o padrão dos já existentes no repositório, ou seja, poderia ser: _MapeamentoRestricaoEnvioComponentesDigitaisTest.php_ ao invés de "MapEnvioCompDigitaisTest";

- [ ] **2.** Criar os testes funcionais também para as versões do SEI 3 e SEI 4;

- [ ] **3.** Corrigir a seguinte falha na execução do teste em questão:

![image](https://github.com/pengovbr/mod-sei-pen/assets/87980947/da2c3615-0a74-48c0-add8-f20b53ace08c)

- [ ] **4.** O _assert_ (na linha 40) deveria validar todos os itens na lista, que foram incluídos na criação, no caso em questão, seria os campos: 'Repositórios de Estruturas Organizacionais' e 'Órgão/Unidade';

- [ ] **5.** Criar um _test case_ para alterar um mapeamento de restrição de envio de componentes digitais;

- [ ] **6.** Criar um _test case_ para excluir um mapeamento de restrição de envio de componentes digitais;

- [ ] **7.** Criar um _test case_ para pesquisar um mapeamento de restrição de envio de componentes digitais;

- [ ] **8.** Criar um _test case_ para imprimir um mapeamento de restrição de envio de componentes digitais.

2023-11-21 14:16 UTC, closed without merging

2023-11-21 14:16 UTC, Mauro1706 commented
Devido a quantidade de commits desnecessários foi criado um novo PR para solucionar correções apontadas https://github.com/pengovbr/mod-sei-pen/pull/351#pullrequestreview-1665025793
PR: https://github.com/pengovbr/mod-sei-pen/pull/397