feat: Foi adicionado uma valicação impedindo de um usuário assinar um…
pengovbr/mod-sei-pen pull request #352
Opened 2023-08-17 17:02 UTC by MatheusMarques80

… documento que tenha sido tramitado anteriormente.

2023-09-11 21:17 UTC, gicastephanou approved these changes
A validação está Ok.

2023-09-26 22:38 UTC, caduvieira commented
@gicastephanou @MatheusMarques80 faltou a parte do prepararAssinaturaDocumento

CONTEXTO_ORGAO_A_DB_SIP_DSN faltou adicionar nos envs modelos.

2023-09-26 22:39 UTC, caduvieira commented
E o código não percorre o array. Caso tenha mais de um documento sendo assinado pode continuar com o problema. Favor corrigir

2023-09-26 22:42 UTC, caduvieira commented
Os testes devem ser criados para o SEI3, SEI4 e SUPER. Só consta os testes para o SUPER

2023-10-02 17:06 UTC, gicastephanou requested changes
Conforme mensagem do Cadu, os testes devem ser criados para o SEI3, SEI4 e SUPER. Só consta os testes para o SUPER.

2023-10-27 19:08 UTC, carlosevmelo commented
Prezados, boa tarde.

Após análise do código fonte dos testes, foi identificado que existem querys SQL, conforme figura abaixo:

![image](https://github.com/pengovbr/mod-sei-pen/assets/15729050/31a192db-a6b8-476d-a442-dd5afe887462)


Por gentileza, adotar como boas práticas a utilização dos Fixtures existentes, ou se necessário, criar novos conforme figura abaixo:

![image](https://github.com/pengovbr/mod-sei-pen/assets/15729050/d6c917df-af28-42cd-b92a-7cbee81ac1b6)

2024-03-14 20:18 UTC, closed without merging