339 melhoria mensagem recusa
pengovbr/mod-sei-pen pull request #356
Opened 2023-08-30 14:44 UTC by michael-ferreira2022

Closes #339

2023-08-30 14:46 UTC, michael-ferreira2022 commented
https://github.com/pengovbr/mod-sei-pen/assets/121502868/2d469758-b96a-4138-9a91-12ece7e4b842

2023-09-11 15:36 UTC, gicastephanou approved these changes
Bom dia,
A melhoria de mensagem foi realizada.

2023-10-04 18:46 UTC, sergioadao requested changes
Prezado, @michael-ferreira2022, ao tentar atualizar a _branch_ michael-ferreira2022-339-melhoria-mensagem-recusa em meu ambiente local, houve conflito no arquivo: _ReceberProcedimentoRN.php_, como você pode observar no _print_ abaixo:



![image](https://github.com/pengovbr/mod-sei-pen/assets/87815724/e93f172a-fb8d-4d3b-b831-3f166984b10d)

2023-10-06 12:59 UTC, michael-ferreira2022 reviewed
Conflito resolvido

2023-10-18 18:44 UTC, sergioadao requested changes
@yuribitu, mensagem não alterada para aquela solicitada na ISSUE 339.

![image](https://github.com/pengovbr/mod-sei-pen/assets/87815724/fa57cfbc-f519-4024-99d2-47ec6cd438db)

Mensagem solicitada:
**O processo/ documento avulso foi recusado: Um processo com o número de protocolo XXXXXX.XXXXXX/XXXXXX -XX já existe no sistema de destino. OBS: A recusa é um das três formas de conclusão de trâmite. Portanto, não é um erro.**

2023-10-25 18:16 UTC, sergioadao requested changes
@mrglaydson, mensagem solicitada não implementada.

O processo/ documento avulso foi recusado: Um processo com o número de protocolo XXXXXX.XXXXXX/XXXXXX -XX já existe no sistema de destino. OBS: A recusa é um das três formas de conclusão de trâmite. Portanto, não é um erro.

Segue arquivo com as teslas do teste.

[issue_339.pdf](https://github.com/pengovbr/mod-sei-pen/files/13169309/issue_339.pdf)

2023-10-25 19:19 UTC, closed without merging

2023-10-25 19:19 UTC, Mauro1706 commented
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/378