354 mapeamento de hipoteses legais recupera hipoteses legais inativas na tela
pengovbr/mod-sei-pen pull request #372
Opened 2023-10-20 19:45 UTC by Mauro1706

Closes: #354

2023-10-20 19:47 UTC, mrglaydson approved these changes

2023-10-24 13:31 UTC, sergioadao requested changes
@Mauro1706, bom dia......a tela Hipóteses Legais Inativas no Portal de Administração não é apreentada.

![image](https://github.com/pengovbr/mod-sei-pen/assets/87815724/90de854b-4a48-41c8-8963-35c49c6dca1c)

2023-10-27 11:38 UTC, Mauro1706 commented
@sergioadao a tela do "Portal de Administração" e externa ao sistema.
Grato.

2023-10-27 11:45 UTC, Mauro1706 commented
Segue evidência da correção do bug:

https://github.com/pengovbr/mod-sei-pen/assets/83025710/0d79c50b-5f8a-48cd-8c72-107250edc4fe

2023-11-01 18:07 UTC, sergioadao approved these changes
@Mauro1706..filtro de hipóteses inativas implementado. 

Antes da aplicação da PR 372:

![issue_354-antes-PR-372](https://github.com/pengovbr/mod-sei-pen/assets/87815724/0230175f-e238-44c7-845e-3d395bb5ba85)

Após aplicar a PR 372:

![issue_354-apos-PR-372](https://github.com/pengovbr/mod-sei-pen/assets/87815724/988773ce-9644-48ac-9680-fdd0f8d65b25)

2024-06-03 20:06 UTC, caduvieira commented
Por favor refazer o PR somente com os commits necessários.

2024-06-06 12:19 UTC, Mauro1706 commented
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/512

2024-06-06 12:19 UTC, closed without merging