Mapeamento de tipos de processo, reativar mapeamento órgão  externo
pengovbr/mod-sei-pen pull request #386
Opened 2023-11-07 12:15 UTC by mrglaydson

Adicionar botão para ativação e desativação de mapeamento,
Adicionar teste funcional para super, sei4 e sei3

Closes #253

2023-11-08 17:41 UTC, sergioadao requested changes
- Após DESATIVAR um relacionamento ao selecionar o mesmo relacionamento e clicar sobre o botão Desativar a mensagem “Relacionamento entre órgãos foi desativado com sucesso” é exibida.

- Já no caso do relacionamento estar Ativo este comportamento não ocorre pois o botão Reativar não é exibido.

![issue_253_ 08-11-2023 10-56](https://github.com/pengovbr/mod-sei-pen/assets/87815724/de27b3ed-5664-4a30-987e-428bf045d54d)

2023-11-08 20:09 UTC, sergioadao requested changes
Após o cadastro do relacionamento o botão DESATIVAR é apresentado.
Na sequência, com o campo ESTADO setado para ATIVO o relacionamento inativado não aparece mais.
Contudo, mudando o campo ESTADO para INATIVO o relacionamento DESATIVADO reaparece, porém o BOTÃO de REATIVAR não aparece, bem como o ícone de ativar/reativar não aparece.

![erro_issue_253_08-11-2023 16-58](https://github.com/pengovbr/mod-sei-pen/assets/87815724/78233542-ebdc-4edb-964b-3af19c2eb467)

2023-11-08 20:43 UTC, mrglaydson commented
> Após o cadastro do relacionamento o botão DESATIVAR é apresentado. Na sequência, com o campo ESTADO setado para ATIVO o relacionamento inativado não aparece mais. Contudo, mudando o campo ESTADO para INATIVO o relacionamento DESATIVADO reaparece, porém o BOTÃO de REATIVAR não aparece, bem como o ícone de ativar/reativar não aparece.
> 
> ![erro_issue_253_08-11-2023 16-58](https://user-images.githubusercontent.com/87815724/281530292-78233542-ebdc-4edb-964b-3af19c2eb467.gif) [ ![erro_issue_253_08-11-2023 16-58](https://user-images.githubusercontent.com/87815724/281530292-78233542-ebdc-4edb-964b-3af19c2eb467.gif) ](https://user-images.githubusercontent.com/87815724/281530292-78233542-ebdc-4edb-964b-3af19c2eb467.gif) [ ](https://user-images.githubusercontent.com/87815724/281530292-78233542-ebdc-4edb-964b-3af19c2eb467.gif)

@sergioadao Esse essa opção de reativar/ativar não está ativada para o perfil do seu usuário, entra no SIP, no menu perfil, caso esteja usando um usuário de teste, selecione a opção 'administrador', filtre pelo o recurso map_orgao, marque os recursos faltantes e clique em salvar.

Ao deslogar e logar novamente no SEI, já deve aparecer as opções faltantes.

2023-11-09 13:33 UTC, sergioadao requested changes
@mrglaydson....confirmado que o problema indicado anteriormente decorreu da falta de privilégio do usuário ADMINISTRADOR. Após a configuração correta via SIP o problema não ocorreu mais. Segue passo-a-passo para a correta configuração do usuário no SIP.

![issue_253_privilegios_usuario_administrador_sip_09-11-2023 10-02](https://github.com/pengovbr/mod-sei-pen/assets/87815724/b802e677-d80f-4132-a453-00c3adb32406)

Abaixo segue evidência do funcionamento correto da funcionalidade de cadastrar, desativar e reativar um relacionamento de processo. Teste versão SEI 4 / SUPER.

![teste_issue_253_desativar_ativar_relacionamento_ 09-11-2023 10-21](https://github.com/pengovbr/mod-sei-pen/assets/87815724/250526e7-990f-4ccb-8cdf-188f445cada2)

2023-11-18 03:03 UTC, davidnascimento1618 requested changes
Prezado @mrglaydson, atribuir um nome mais intuitivo aos testes funcionais (isso inclui nomenclatura dos arquivos e classes correlacionadas), ou seja, um sugestão seria: '_MapeamentoTipoProcessoDesativarReativarTest_' ao invés de '_TramiteMapeamentoOrgaoExternoTest_'.

2023-11-20 20:04 UTC, Mauro1706 commented
Resolvido no PR https://github.com/pengovbr/mod-sei-pen/pull/396

2023-11-20 20:04 UTC, closed without merging