Feature/251 mapeamento de tipos de processos gerar tela listar
pengovbr/mod-sei-pen pull request #401
Opened 2023-11-24 22:58 UTC by Mauro1706

Closes: #251 #250 #253 #257 #384

2023-11-24 23:00 UTC, Mauro1706 commented
Closes: #250

2023-11-28 21:21 UTC, Mauro1706 commented
Closes: #256

2023-11-30 14:50 UTC, sergioadao requested changes
@Mauro1706 .....ajustar tamanho do nome de variaveis com tamanho acima de 30 caracteres - sei_atualizar_versao_modulo_pen.php.

2023-12-14 22:28 UTC, Mauro1706 commented
Resolvido com um commit no PR https://github.com/pengovbr/mod-sei-pen/pull/403

2023-12-14 22:28 UTC, closed without merging