feat: adicionar estrutura base para funcionamento do composer no módulo
pengovbr/mod-sei-pen pull request #583
Opened 2024-08-16 01:54 UTC by mrglaydson

- Estruturar base para funcionamento de pacotes instalados pelo o composer no módulo
- Adicionar Guzzle ^7.0 no composer do módulo
- Execultar autodamp

2024-09-17 13:01 UTC, caduvieira requested changes

2024-09-17 13:01 UTC, caduvieira commented on src/rn/EnviarReciboTramiteRN.php
> -      if($operacao->situacao == ProcessoEletronicoRN::$STA_SITUACAO_TRAMITE_COMPONENTES_RECEBIDOS_DESTINATARIO) {
Deixou de ser uma propriedade?

2024-09-17 13:01 UTC, caduvieira commented on src/rn/ExpedirProcedimentoRN.php
> -            $arrComponentesDigitais = is_array($objDoc->componenteDigital) ? $objDoc->componenteDigital : array($objDoc->componenteDigital);
Mudou o nome da propriedade?

2024-09-19 18:08 UTC, caduvieira commented on src/rn/ProcessoEletronicoRN.php
> -			$objResultado->metadados->processo->documento = $arrObjMetaDocumento;
Aqui vamos pegar só o primeiro? Não pode vir mais dados?

2024-09-19 18:09 UTC, caduvieira commented on src/rn/ProcessoEletronicoRN.php
> -      if ($e instanceof \SoapFault && !empty($e->detail->interoperabilidadeException->codigoErro) && $e->detail->interoperabilidadeException->codigoErro == '0005') {
O código do erro continua nesse caminho?

2024-09-24 14:50 UTC, higodf commented on src/rn/ProcessoEletronicoRN.php
> +	  $this->strBaseUri = 'https://homolog.api.processoeletronico.gov.br';
Deveria pegar do arquivo de configuração do módulo.

2024-09-24 14:50 UTC, higodf commented on src/rn/ProcessoEletronicoRN.php
> +      $strWSDL = $this->strEnderecoWebService . '/interoperabilidade/soap/v3/?wsdl';
Não entendi. Vai continuar usando o SOAP?

2024-09-26 12:45 UTC, mrglaydson commented on src/rn/EnviarReciboTramiteRN.php
> -      if($operacao->situacao == ProcessoEletronicoRN::$STA_SITUACAO_TRAMITE_COMPONENTES_RECEBIDOS_DESTINATARIO) {
Sim, Soap retorna tudo como objeto/array de objetos e o rest retorna tudo como Array

2024-09-26 13:04 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +        'protocolo' => utf8_encode($objProcedimentoDTO->getStrProtocoloProcedimentoFormatado()),
função utf8_encode foi descontinuada no PHP.

2024-09-26 13:05 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +   // $this->adicionarProcessosApensadosREST($objProcesso, $arrIdProcessoApensado);
Retirar código comentado

2024-09-26 13:09 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +      // $objProcesso = [];
Retirar código comentado

2024-09-26 13:10 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +        $objProcesso['interessados'] = [];
O correto não seria manter a atribuição como "array()"?

2024-09-26 13:11 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +       // $documento['retirado'] = $documentoDTO->getStrStaEstadoProtocolo() == ProtocoloRN::$TE_DOCUMENTO_CANCELADO ? false : true;
Porque a regra foi retirada?

2024-09-26 13:12 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +           //  $documento['protocoloDoProcessoAnexado'] = $documentoDTO->getStrProtocoloProcedimentoFormatado();
Porque a regra foi retirada?

2024-09-26 13:12 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +          $documento['hipoteseLegal'] = []; // Inicializando a chave 'hipoteseLegal' como um array
O correto não seria manter a atribuição como "array()"?

2024-09-26 13:13 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +        $documento['produtor'] = []; // Inicializando a chave 'produtor' como um array
O correto não seria manter a atribuição como "array()"?

2024-09-26 13:13 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +          $documento['produtor']['unidade'] = []; // Inicializando a chave 'unidade' como um array
O correto não seria manter a atribuição como "array()"?

2024-09-26 13:13 UTC, higodf commented on src/rn/ExpedirProcedimentoRN.php
> +            $documento['componentesDigitais'] = []; // Inicializando 'componentesDigitais' como um array
O correto não seria manter a atribuição como "array()"?

2024-09-26 13:18 UTC, higodf commented on src/rn/ProcessoEletronicoRN.php
> +        $arrObjRepositorioDTO = [];
O correto não seria manter a atribuição como "array()"?

2024-09-27 18:01 UTC, higodf requested changes

2024-09-27 18:01 UTC, higodf commented on tests_sei41/funcional/composer.json
>          "besimple/soap": "*",
Retirar do composer.

2024-09-27 18:01 UTC, higodf commented on tests_super/funcional/composer.json
>          "besimple/soap": "*",
Retirar do composer

2024-10-31 12:16 UTC, closed without merging